# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bareBones-os
description: Personal Fedora Atomic desktop image built with BlueBuild
base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: latest

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship
    install:
      packages:
        - jetbrains-mono-fonts
        - google-noto-sans-vf-fonts
        - google-noto-serif-vf-fonts
        - google-noto-sans-mono-vf-fonts
        - micro
        - starship
        - git
        - neovim
        - nnn
        - zsh
        - lm_sensors
        - nvidia-container-toolkit
        - podman-compose
        - tailscale
        - chezmoi
        - cliphist
        - fuzzel
        - hyprpolkitagent
        - hyprshot
        - nwg-look
        - SwayNotificationCenter
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - pipewire-config-raop

  - type: systemd
    system:
      enabled:
        - bluetooth.service
        - tailscaled.service

  - type: default-flatpaks@v2
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - app.zen_browser.zen
          - com.discordapp.Discord
          - com.bitwarden.desktop
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - org.kde.kate
          - org.kde.okular
          - com.github.jeromerobert.pdfarranger
          - com.visualstudio.code
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.podman_desktop.PodmanDesktop
          - org.gnome.clocks
          - org.gnome.Loupe
          - com.valvesoftware.Steam
          - org.prismlauncher.PrismLauncher
          - org.photoqt.PhotoQt
          - org.qbittorrent.qBittorrent
          - com.calibre_ebook.calibre

  - type: signing
